const links = [
    { name: " Photo 1 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard.jpg"},
    { name: " Photo 2 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (1).jpg" },
    { name: " Photo 3 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (2).jpg" },
    { name: " Photo 4 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (3).jpg" },
    { name: " Photo 5 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (4).jpg" },
    { name: " Photo 6 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (5).jpg" },
    { name: " Photo 7 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (6).jpg" },
    { name: " Photo 8 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (7).jpg" },
    { name: " Photo 9 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (8).jpg" },
    { name: " Photo 10 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (9).jpg" },
    { name: " Photo 11 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (10).jpg" },
    { name: " Photo 12 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (11).jpg" },
    { name: " Photo 13 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (12).jpg" },
    { name: " Photo 14 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (13).jpg" },
    { name: " Photo 15 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (14).jpg" },
    { name: " Photo 16 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (15).jpg" },
    { name: " Photo 17 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (16).jpg" },
    { name: " Photo 18 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (17).jpg" },
    { name: " Photo 19 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (18).jpg" },
    { name: " Photo 20 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (19).jpg" },
    { name: " Photo 21 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (20).jpg" },
    { name: " Photo 22 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (21).jpg" },
    { name: " Photo 23 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (22).jpg" },
    { name: " Photo 24 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (23).jpg" },
    { name: " Photo 25 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (24).jpg" },
    { name: " Photo 26 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (25).jpg" },
    { name: " Photo 27 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (26).jpg" },
    { name: " Photo 28 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (27).jpg" },
    { name: " Photo 29 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (28).jpg" },
    { name: " Photo 30 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (29).jpg" },
    { name: " Photo 31 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (30).jpg" },
    { name: " Photo 32 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (31).jpg" },
    { name: " Photo 33 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (32).jpg" },
    { name: " Photo 34 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (33).jpg" },
    { name: " Photo 35 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (34).jpg" },
    { name: " Photo 36 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (35).jpg" },
    { name: " Photo 37 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (36).jpg" },
    { name: " Photo 38 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (37).jpg" },
    { name: " Photo 39 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (38).jpg" },
    { name: " Photo 40 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (39).jpg" },
    { name: " Photo 41 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (40).jpg" },
    { name: " Photo 42 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (41).jpg" },
    { name: " Photo 43 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (42).jpg" },
    { name: " Photo 44 ", url: "https://lab4cloudgroup.blob.core.windows.net/kgl4blob/Dahlonega Graveyard (43).jpg" }
];
export default links;